/**
 * @file
 */

#pragma once

#include <glm/common.hpp>
#include <glm/vec2.hpp>
#include <math.h>
#include <stdint.h>

namespace voxelpathtracer {
namespace sampling {

/**
 * Integer-only hash used to seed every renderer sampling dimension.
 *
 * Keep the operations and constants in sync with the WGSL version.
 * WGSL u32 arithmetic has the same wrapping behavior.
 */
inline uint32_t hash32(uint32_t value) {
	value = (value ^ 61u) ^ (value >> 16u);
	value *= 9u;
	value ^= value >> 4u;
	value *= 0x27d4eb2du;
	value ^= value >> 15u;
	return value;
}

/**
 * Return one reproducible value in [0, 1) and advance the state.
 */
inline float next1D(uint32_t &state) {
	state = hash32(state);
	return (float)(state >> 8u) * (1.0f / 16777216.0f);
}

// ---------------------------------------------------------------------------
// Owen-scrambled Sobol (CPU). Bit-exact twin of the WGSL `sobol1D`/`sobol2D`.
// ---------------------------------------------------------------------------

// Reverse the 32 bits of x. Matches the WGSL `reverseBits` builtin.
inline uint32_t reverseBits32(uint32_t x) {
	x = ((x >> 1u) & 0x55555555u) | ((x & 0x55555555u) << 1u);
	x = ((x >> 2u) & 0x33333333u) | ((x & 0x33333333u) << 2u);
	x = ((x >> 4u) & 0x0f0f0f0fu) | ((x & 0x0f0f0f0fu) << 4u);
	x = ((x >> 8u) & 0x00ff00ffu) | ((x & 0x00ff00ffu) << 8u);
	return (x >> 16u) | (x << 16u);
}

// Count trailing zeros of a nonzero 32-bit value. Matches WGSL
// `firstTrailingBit`.
inline uint32_t trailingZeros32(uint32_t x) {
	static const uint8_t table[32] = {0, 1, 28, 2, 29, 14, 24, 3, 30, 22, 20, 15, 25, 17, 4, 8,
									  31, 27, 13, 23, 21, 19, 16, 7, 26, 12, 18, 6, 11, 5, 10, 9};
	return table[((x & (~x + 1u)) * 0x077CB531u) >> 27u];
}

// Burley's hash-based Owen scrambling ("Practical Hash-based Owen Scrambling",
// JCGT 2020). Bit-exact with the WGSL twin.
inline uint32_t sobolOwenHash(uint32_t x, uint32_t seed) {
	x ^= x * 0x3d20adea;
	x += seed;
	x *= (seed >> 16u) | 1u;
	x ^= x * 0x05526c56;
	x ^= x * 0x53a22864;
	return x;
}

// Sobol direction integers for dimension 1 (primitive polynomial x^2 + x + 1),
// generated by the Joe & Kuo recurrence. V[1][k] = m[k] << (31 - k).
// Dimension 0 is the radical inverse (base 2).
inline constexpr uint32_t kSobolDim1Directions[32] = {
	1u, 3u, 3u, 9u, 29u, 23u, 71u, 197u, 209u, 627u, 1907u, 1369u,
	4109u, 12327u, 12407u, 36949u, 119041u, 94979u, 291587u, 809225u,
	855325u, 2565911u, 7829319u, 5592517u, 16777681u, 50332019u,
	50332787u, 150998105u, 486542605u, 385885991u, 1191212919u, 3305133397u};

// Raw (unscrambled) Sobol integer for a dimension. 0 = radical inverse,
// 1 = second dimension. Uses the direct bits of `index` (not Gray code), which
// is the stateless definition of the Sobol sequence.
inline uint32_t sobolRaw(uint32_t index, uint32_t dim) {
	if (dim == 0u) {
		return reverseBits32(index);
	}
	uint32_t v = 0u;
	uint32_t n = index;
	while (n != 0u) {
		const uint32_t k = trailingZeros32(n);
		v ^= kSobolDim1Directions[k] << (31u - k);
		n &= n - 1u;
	}
	return v;
}

// Owen-scrambled Sobol sample in [0, 1) for a dimension and seed.
inline float sobolSample(uint32_t index, uint32_t dim, uint32_t seed) {
	return (float)(sobolOwenHash(sobolRaw(index, dim), seed) >> 8u) * (1.0f / 16777216.0f);
}

// 1D Owen-scrambled Sobol. The scramble selects an independent sequence.
inline float sobol1D(uint32_t index, uint32_t scramble) {
	return sobolSample(index, 0u, hash32(scramble));
}

// 2D Owen-scrambled Sobol with independent per-axis sequences.
inline glm::vec2 sobol2D(uint32_t index, uint32_t scramble) {
	const float x = sobolSample(index, 0u, hash32(scramble ^ 0x68bc21ebu));
	const float y = sobolSample(index, 1u, hash32(scramble ^ 0x02e5be93u));
	return glm::vec2(x, y);
}

/** Henyey-Greenstein phase. Keep in sync with the WGSL twin. */
inline float henyeyGreenstein(float g, float cosTheta) {
	const float gg = glm::clamp(g, -0.95f, 0.95f);
	const float g2 = gg * gg;
	const float den = 1.0f + g2 - 2.0f * gg * cosTheta;
	return (1.0f - g2) / (12.566370614359172f * den * sqrtf(glm::max(den, 1.0e-8f)));
}

} // namespace sampling
} // namespace voxelpathtracer
